--CREATE DATABASE LibraryDB;
GO
USE LibraryDB;

DROP TABLE IF EXISTS Loans;
DROP TABLE IF EXISTS bookGenres;
DROP TABLE IF EXISTS bookAuthors;

DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS readers;
DROP TABLE IF EXISTS books;

CREATE TABLE authors (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FullName NVARCHAR(200) NOT NULL,
	BirthDate DATE,
	Country NVARCHAR(100) NOT NULL,
	IsALive BIT NOT NULL DEFAULT 1
);

CREATE TABLE genres (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name NVARCHAR(100) NOT NULL
);

CREATE TABLE readers (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	FullName NVARCHAR(200) NOT NULL,
	Email NVARCHAR(200) NOT NULL,
	RegisteredAt DATETIME NOT NULL DEFAULT GETDATE(),
	IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE books (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Title NVARCHAR(300) NOT NULL,
	ISBN NVARCHAR(20) NOT NULL,
	Price DECIMAL(10, 2) NOT NULL,
	PublishedAt DATETIME NOT NULL,
	InStock BIT NOT NULL DEFAULT 1
);

CREATE TABLE bookAuthors (
	BookId UNIQUEIDENTIFIER NOT NULL REFERENCES books(Id),
	AuthorId UNIQUEIDENTIFIER NOT NULL REFERENCES authors(Id),
	PRIMARY KEY (BookId, AuthorId)
);

CREATE TABLE bookGenres (
	BookId UNIQUEIDENTIFIER NOT NULL REFERENCES books(Id),
	GenreId UNIQUEIDENTIFIER NOT NULL REFERENCES genres(Id),
	PRIMARY KEY (BookId, GenreId)
);

CREATE TABLE Loans (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	BookId UNIQUEIDENTIFIER NOT NULL REFERENCES books(Id),
	ReaderId UNIQUEIDENTIFIER NOT NULL REFERENCES readers(Id),
	LoanedAt DATETIME NOT NULL DEFAULT GETDATE(),
	ReturnedAt DATETIME NULL,
	IsReturned BIT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX UX_Books_ISBN ON books(ISBN);

CREATE UNIQUE INDEX UX_Readers_Email ON readers(Email);

